export const INITIALIZE_STATE = 'INITIALIZE_STATE';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_NEW_ACCOUNT = 'SET_NEW_ACCOUNT';

export const UPDATE_SELECTED_ACC = 'UPDATE_SELECTED_ACC';

export const ADD_TRANSFER_TRANSACTION = 'ADD_TRANSFER_TRANSACTION';